### ISSUE TITLE
Не все зависимости, необходимые для работы системы были залиты

### ISSUE THREAD

**Issue by brainpusher** [CrazyPandaLimited/assets-system#1]
1. В классе **AssetBundleLoader** есть зависимость на `using CrazyPanda.UnityCore.Utils;` однако ее нет ни в одном из проектов в репозитории. 
2. В классе **ResourceStorageRemoteBundleTests** есть зависимость на `using CrazyPanda.UnityCore.Serialization;`, так же нет нигде ее.
3.  В классе **AssetBundlesProvider** есть зависимость на `using CrazyPanda.UnityCore.DeliverySystem;`, то же самое. Только тут еще хуже, так как видимо там объявлен интерфейс/абстрактный класс `CrazyPanda.UnityCore.DeliverySystem.AssetBundlesProvider`. Соотвественно нет в этом же классе и метода  `this.GetPlatformPrefix()`

Дозалейте пожалуйста необходимые пакеты, в противном же случае данной системой просто невозможно пользоваться.

**Comment by artificialpancakes** [comment]
Привет. Обновили все репы и добавили UtilsCollectionSystem, как раз таки недостающая зависимость:
- assets-system
- simple-promises
- OrderedNotifySet
- MessagesFlow
- UtilsCollectionSystem (new)

**Comment by brainpusher** [comment]
> Привет. Обновили все репы и добавили UtilsCollectionSystem, как раз таки недостающая зависимость:
> 
>     * assets-system
> 
>     * simple-promises
> 
>     * OrderedNotifySet
> 
>     * MessagesFlow
> 
>     * UtilsCollectionSystem (new)

Большое Вам спасибо!

**Comment by artificialpancakes** [comment]
@brainpusher 
Привет. Если проблем больше не осталось - закрой issue, пожалуйста.
